version: '3'

services:
    
  rnaget-mongo:
    image: mongo:6.0
    container_name: "${DB_HOST}"
    env_file:
      - .env
    restart: always
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - /data/rnaget-data:/data/db
    ports:
      - "${DB_PORT}:27017"
    networks:
      - monstre

  rnaget-nginx:
    image: gitlab.linux.crg.es:5005/monstre/rnaget-beacon-demo/rnaget-nginx
    container_name: ${NGINX_HOST}
    restart: always
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - BASE_PATH=${BASE_PATH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rnaget-nginx.rule=(Host(`genome.crg.es`) || Host(`genome.crg.cat`) || Host(`genome.crg.eu`)) && PathPrefix(`/rnaget-beacon`)"
      - "traefik.http.routers.rnaget-nginx.tls=true"
      - "traefik.http.routers.rnaget-nginx.entrypoints=web_https"
      - "traefik.http.services.rnaget-nginx.loadBalancer.server.port=80"
    ports:
        - "94:${API_PORT}"
    networks:
      - monstre

  rnaget-server:
    image: gitlab.linux.crg.es:5005/monstre/rnaget-beacon-demo/rnaget-server
    container_name: ${API_HOST}
    restart: always
    volumes:
      - ./server:/server
    env_file:
      - .env
    depends_on:
      - rnaget-redis
    networks:
      - monstre

  rnaget-celery:
    image: gitlab.linux.crg.es:5005/monstre/rnaget-beacon-demo/rnaget-server
    command: celery --app app.celery_app worker --loglevel=info --autoscale=1,1 --max-tasks-per-child=1
    restart: always
    volumes:
      - ./server:/server
    env_file:
      - .env
    depends_on:
      - rnaget-server
      - rnaget-mongo
      - rnaget-redis
    networks:
      - monstre

  rnaget-redis:
    image: "redis:alpine"
    expose:
      - "6378"
    networks:
      - monstre
networks:
  monstre:
    external:
      name: monstre
